# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Dy6Jcz7602HhWp3G64vwTBTQ56eOcEyM
"""

import matplotlib.pyplot as plt
import numpy as np
x=np.array([0,6])
y=np.array([0,250])
plt.plot(x,y)
plt.show()

import matplotlib.pyplot as plt
import numpy as np
x=np.array([1,2,6,8])
y=np.array([3,8,1,10,])
plt.plot(x,y)
plt.show()

import matplotlib.pyplot as plt

# Uyning to'rtburchak qismi uchun x va y koordinatalarini belgilash
x_rectangle = [1, 1, 5, 5, 1]
y_rectangle = [1, 5, 5, 1, 1]

# Tomning uchburchak qismi uchun x va y koordinatalarini belgilash
x_triangle = [1, 3, 5, 1] # Uchburchakning uchlari: chap burchak, tepa, o'ng burchak, chap burchakka qaytish
y_triangle = [5, 7, 5, 5] # Uchburchakning uchlari: chap burchak, tepa, o'ng burchak, chap burchakka qaytish

# Grafik yaratish
plt.figure(figsize=(8, 6)) # Grafik o'lchamini sozlash

# To'rtburchakni chizish
plt.plot(x_rectangle, y_rectangle, label='Uyning asosiy qismi', color='blue', linewidth=2)

# Uchburchakni chizish (tom)
plt.plot(x_triangle, y_triangle, label='Tom', color='green', linewidth=2)

# O'qlarga nom berish
plt.xlabel('X oʻqi')
plt.ylabel('Y oʻqi')

# Grafikga sarlavha berish
plt.title('Matplotlib yordamida uy shakli')

# Legendani ko'rsatish
plt.legend()

# Gridni yoqish
plt.grid(True)

# O'qlarning chegarasini sozlash (agar kerak bo'lsa)
plt.xlim(0, 6)
plt.ylim(0, 8)

# Aspekt nisbatini tenglashtirish
plt.axis('equal')

# Grafikni ko'rsatish
plt.show()

import numpy as np
import matplotlib.pyplot as plt

# 2. Yurak shaklini yaratish uchun t parametrini aniqlang
t = np.linspace(0, 2 * np.pi, 1000)

# 3. Yurak shaklining x va y koordinatalarini parametrik tenglamalar yordamida hisoblang
x = 16 * (np.sin(t)**3)
y = 13 * np.cos(t) - 5 * np.cos(2*t) - 2 * np.cos(3*t) - np.cos(4*t)

# 5. Yangi grafik yarating va o'lchamini sozlang
plt.figure(figsize=(8, 8))

# 6. Hisoblangan x va y koordinatalarini chizing
plt.plot(x, y, color='red', linewidth=2)

# Grafikni estetik jihatdan yaxshilash
plt.title('Matplotlib yordamida yurak shakli')
plt.xlabel('X oʻqi')
plt.ylabel('Y oʻqi')
plt.grid(True)
plt.axis('equal') # Yurak shaklini to'g'ri ko'rsatish uchun

# 7. Grafikni ko'rsating
plt.show()